modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/dmmttba/issues"
license="MIT"

[[mods]]
modId="dmmttba"
version="${file.jarVersion}"
displayName="Don't Make Me Turn This Boat Around"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dmmttba"
authors="Mrbysco"
logoFile="icon.png"
description='''
Never have to turn your boat again!
'''
credits="GenerikB"

[[dependencies.dmmttba]]
modId="minecraft"
type="REQUIRED"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.dmmttba]]
modId="neoforge"
type="REQUIRED"
versionRange="[26.1.1.0-beta,)"
ordering="NONE"
side="BOTH"